// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/hello_streaming.proto

package com.example.nettygrpcdemo1;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:manualflowcontrol.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
