// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/route_guide.proto

package com.example.nettygrpcdemo1;

public interface RectangleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.Rectangle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.routeguide.Point lo = 1;</code>
   */
  boolean hasLo();
  /**
   * <code>.routeguide.Point lo = 1;</code>
   */
  com.example.nettygrpcdemo1.Point getLo();
  /**
   * <code>.routeguide.Point lo = 1;</code>
   */
  com.example.nettygrpcdemo1.PointOrBuilder getLoOrBuilder();

  /**
   * <code>.routeguide.Point hi = 2;</code>
   */
  boolean hasHi();
  /**
   * <code>.routeguide.Point hi = 2;</code>
   */
  com.example.nettygrpcdemo1.Point getHi();
  /**
   * <code>.routeguide.Point hi = 2;</code>
   */
  com.example.nettygrpcdemo1.PointOrBuilder getHiOrBuilder();
}
